// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[PrimaryKey("MaDbh", "MaSp")]
[Table("CTBH")]
public partial class Ctbh
{
    [Key]
    [Column("MaDBH")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaDbh { get; set; }

    [Key]
    [Column("MaSP")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaSp { get; set; }

    [Column("SLB")]
    public int Slb { get; set; }

    [Column("DGB", TypeName = "decimal(18, 2)")]
    public decimal Dgb { get; set; }

    [ForeignKey("MaDbh")]
    [InverseProperty("Ctbhs")]
    public virtual DonBanHang MaDbhNavigation { get; set; }

    [ForeignKey("MaSp")]
    [InverseProperty("Ctbhs")]
    public virtual SanPham MaSpNavigation { get; set; }
}