// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[PrimaryKey("MaDmh", "MaSp")]
[Table("CTMH")]
public partial class Ctmh
{
    [Key]
    [Column("MaDMH")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaDmh { get; set; }

    [Key]
    [Column("MaSP")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaSp { get; set; }

    [Column("SLM")]
    public int Slm { get; set; }

    [Column("DGM", TypeName = "decimal(18, 2)")]
    public decimal Dgm { get; set; }

    [ForeignKey("MaDmh")]
    [InverseProperty("Ctmhs")]
    public virtual DonMuaHang MaDmhNavigation { get; set; }

    [ForeignKey("MaSp")]
    [InverseProperty("Ctmhs")]
    public virtual SanPham MaSpNavigation { get; set; }
}