// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("DonBanHang")]
public partial class DonBanHang
{
    [Key]
    [Column("MaDBH")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaDbh { get; set; }

    [Column("NgayBH")]
    public DateOnly NgayBh { get; set; }

    [Required]
    [Column("MaKH")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaKh { get; set; }

    [InverseProperty("MaDbhNavigation")]
    public virtual ICollection<Ctbh> Ctbhs { get; set; } = new List<Ctbh>();

    [ForeignKey("MaKh")]
    [InverseProperty("DonBanHangs")]
    public virtual KhachHang MaKhNavigation { get; set; }
}