// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("DonMuaHang")]
public partial class DonMuaHang
{
    [Key]
    [Column("MaDMH")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaDmh { get; set; }

    [Column("NgayMH")]
    public DateOnly NgayMh { get; set; }

    [Required]
    [Column("MaNCC")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaNcc { get; set; }

    [Required]
    [Column("MaNV")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaNv { get; set; }

    [InverseProperty("MaDmhNavigation")]
    public virtual ICollection<Ctmh> Ctmhs { get; set; } = new List<Ctmh>();

    [ForeignKey("MaNcc")]
    [InverseProperty("DonMuaHangs")]
    public virtual NhaCc MaNccNavigation { get; set; }

    [ForeignKey("MaNv")]
    [InverseProperty("DonMuaHangs")]
    public virtual NhanVien MaNvNavigation { get; set; }
}