// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("HangSX")]
public partial class HangSx
{
    [Key]
    [Column("MaHSX")]
    [StringLength(10)]
    [Unicode(false)]
    public string MaHsx { get; set; }

    [Required]
    [Column("TenHSX")]
    [StringLength(50)]
    public string TenHsx { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string MaNuoc { get; set; }

    [ForeignKey("MaNuoc")]
    [InverseProperty("HangSxes")]
    public virtual Nuoc MaNuocNavigation { get; set; }

    [InverseProperty("MaHsxNavigation")]
    public virtual ICollection<SanPham> SanPhams { get; set; } = new List<SanPham>();
}