// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("KhachHang")]
public partial class KhachHang
{
    [Key]
    [Column("MaKH")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaKh { get; set; }

    [Required]
    [Column("TenKH")]
    [StringLength(50)]
    public string TenKh { get; set; }

    [Required]
    [Column("DienThoaiKH")]
    [StringLength(15)]
    [Unicode(false)]
    public string DienThoaiKh { get; set; }

    [Column("EmailKH")]
    [StringLength(255)]
    public string EmailKh { get; set; }

    [Required]
    [Column("DiaChiKH")]
    [StringLength(255)]
    public string DiaChiKh { get; set; }

    [Column("AnhKH")]
    [StringLength(255)]
    public string AnhKh { get; set; }

    public short MaXa { get; set; }

    [InverseProperty("MaKhNavigation")]
    public virtual ICollection<DonBanHang> DonBanHangs { get; set; } = new List<DonBanHang>();

    [ForeignKey("MaXa")]
    [InverseProperty("KhachHangs")]
    public virtual Xa MaXaNavigation { get; set; }
}