// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("LoaiSP")]
public partial class LoaiSp
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string MaLoai { get; set; }

    [Required]
    [StringLength(50)]
    public string TenLoai { get; set; }

    [InverseProperty("MaLoaiNavigation")]
    public virtual ICollection<SanPham> SanPhams { get; set; } = new List<SanPham>();
}