// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("NhaCC")]
public partial class NhaCc
{
    [Key]
    [Column("MaNCC")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaNcc { get; set; }

    [Required]
    [Column("TenNCC")]
    [StringLength(100)]
    public string TenNcc { get; set; }

    [Required]
    [Column("DienThoaiNCC")]
    [StringLength(15)]
    [Unicode(false)]
    public string DienThoaiNcc { get; set; }

    [Column("EmailNCC")]
    [StringLength(100)]
    [Unicode(false)]
    public string EmailNcc { get; set; }

    [Required]
    [Column("DiaChiNCC")]
    [StringLength(255)]
    public string DiaChiNcc { get; set; }

    public short MaXa { get; set; }

    [InverseProperty("MaNccNavigation")]
    public virtual ICollection<DonMuaHang> DonMuaHangs { get; set; } = new List<DonMuaHang>();

    [ForeignKey("MaXa")]
    [InverseProperty("NhaCcs")]
    public virtual Xa MaXaNavigation { get; set; }

    [InverseProperty("MaNccNavigation")]
    public virtual ICollection<SanPham> SanPhams { get; set; } = new List<SanPham>();
}