// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("NhanVien")]
public partial class NhanVien
{
    [Key]
    [Column("MaNV")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaNv { get; set; }

    [Required]
    [Column("TenNV")]
    [StringLength(50)]
    public string TenNv { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string MatKhau { get; set; }

    [Column("DienThoaiNV")]
    [StringLength(15)]
    [Unicode(false)]
    public string DienThoaiNv { get; set; }

    [Column("DiaChiNV")]
    [StringLength(255)]
    public string DiaChiNv { get; set; }

    [InverseProperty("MaNvNavigation")]
    public virtual ICollection<DonMuaHang> DonMuaHangs { get; set; } = new List<DonMuaHang>();
}