// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("NhomSP")]
public partial class NhomSp
{
    [Key]
    [Column("MaNSP")]
    [StringLength(10)]
    [Unicode(false)]
    public string MaNsp { get; set; }

    [Required]
    [Column("TenNSP")]
    [StringLength(50)]
    public string TenNsp { get; set; }

    [InverseProperty("MaNspNavigation")]
    public virtual ICollection<LoaiSp> LoaiSps { get; set; } = new List<LoaiSp>();
}