// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("Nuoc")]
public partial class Nuoc
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string MaNuoc { get; set; }

    [Required]
    [StringLength(50)]
    public string TenNuoc { get; set; }

    [InverseProperty("MaNuocNavigation")]
    public virtual ICollection<HangSx> HangSxes { get; set; } = new List<HangSx>();
}