// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

public partial class QLBHContext : DbContext
{
    public QLBHContext(DbContextOptions<QLBHContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ctbh> Ctbhs { get; set; }

    public virtual DbSet<Ctmh> Ctmhs { get; set; }

    public virtual DbSet<DonBanHang> DonBanHangs { get; set; }

    public virtual DbSet<DonMuaHang> DonMuaHangs { get; set; }

    public virtual DbSet<KhachHang> KhachHangs { get; set; }

    public virtual DbSet<LoaiSp> LoaiSps { get; set; }

    public virtual DbSet<NhaCc> NhaCcs { get; set; }

    public virtual DbSet<SanPham> SanPhams { get; set; }

    public virtual DbSet<Tinh> Tinhs { get; set; }

    public virtual DbSet<Xa> Xas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Ctbh>(entity =>
        {
            entity.HasOne(d => d.MaDbhNavigation).WithMany(p => p.Ctbhs).HasConstraintName("FK_CTBH_DonBanHang");

            entity.HasOne(d => d.MaSpNavigation).WithMany(p => p.Ctbhs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CTBH_SanPham");
        });

        modelBuilder.Entity<Ctmh>(entity =>
        {
            entity.HasOne(d => d.MaDmhNavigation).WithMany(p => p.Ctmhs).HasConstraintName("FK_CTMH_DonMuaHang");

            entity.HasOne(d => d.MaSpNavigation).WithMany(p => p.Ctmhs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CTMH_SanPham");
        });

        modelBuilder.Entity<DonBanHang>(entity =>
        {
            entity.HasKey(e => e.MaDbh).HasName("PK__DonBanHa__3D8B875D6946004D");

            entity.HasOne(d => d.MaKhNavigation).WithMany(p => p.DonBanHangs).HasConstraintName("FK_DonBanHang_KhachHang");
        });

        modelBuilder.Entity<DonMuaHang>(entity =>
        {
            entity.HasKey(e => e.MaDmh).HasName("PK__DonMuaHa__3D8821AD95954CE1");

            entity.HasOne(d => d.MaNccNavigation).WithMany(p => p.DonMuaHangs).HasConstraintName("FK_DonMuaHang_NhaCC");
        });

        modelBuilder.Entity<KhachHang>(entity =>
        {
            entity.HasKey(e => e.MaKh).HasName("PK__KhachHan__2725CF1EF1FB48F3");

            entity.HasOne(d => d.MaXaNavigation).WithMany(p => p.KhachHangs).HasConstraintName("FK_KhachHang_Xa");
        });

        modelBuilder.Entity<LoaiSp>(entity =>
        {
            entity.HasKey(e => e.MaLoai).HasName("PK__LoaiSP__730A5759C1A9EA6E");
        });

        modelBuilder.Entity<NhaCc>(entity =>
        {
            entity.HasKey(e => e.MaNcc).HasName("PK__NhaCC__3A185DEBE7BDFD75");

            entity.HasOne(d => d.MaXaNavigation).WithMany(p => p.NhaCcs).HasConstraintName("FK_NhaCC_Xa");
        });

        modelBuilder.Entity<SanPham>(entity =>
        {
            entity.HasKey(e => e.MaSp).HasName("PK__SanPham__2725081CCB23E0AB");

            entity.HasOne(d => d.MaLoaiNavigation).WithMany(p => p.SanPhams).HasConstraintName("FK_SanPham_LoaiSP");

            entity.HasOne(d => d.MaNccNavigation).WithMany(p => p.SanPhams).HasConstraintName("FK_SanPham_NhaCC");
        });

        modelBuilder.Entity<Tinh>(entity =>
        {
            entity.HasKey(e => e.MaTinh).HasName("PK__Tinh__4CC54480B8E85529");
        });

        modelBuilder.Entity<Xa>(entity =>
        {
            entity.HasKey(e => e.MaXa).HasName("PK__Xa__272520C9E8691CB3");

            entity.HasOne(d => d.MaTinhNavigation).WithMany(p => p.Xas).HasConstraintName("FK_Xa_Tinh");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}