// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("SanPham")]
public partial class SanPham
{
    [Key]
    [Column("MaSP")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaSp { get; set; }

    [Required]
    [Column("TenSP")]
    [StringLength(50)]
    public string TenSp { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal GiaBan { get; set; }

    [Required]
    [StringLength(50)]
    public string TrangThai { get; set; }

    public int SoLuongTon { get; set; }

    [Column("AnhSP")]
    [StringLength(255)]
    public string AnhSp { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string MaLoai { get; set; }

    [Required]
    [Column("MaNCC")]
    [StringLength(20)]
    [Unicode(false)]
    public string MaNcc { get; set; }

    [Required]
    [Column("MaHSX")]
    [StringLength(10)]
    [Unicode(false)]
    public string MaHsx { get; set; }

    [InverseProperty("MaSpNavigation")]
    public virtual ICollection<Ctbh> Ctbhs { get; set; } = new List<Ctbh>();

    [InverseProperty("MaSpNavigation")]
    public virtual ICollection<Ctmh> Ctmhs { get; set; } = new List<Ctmh>();

    [ForeignKey("MaHsx")]
    [InverseProperty("SanPhams")]
    public virtual HangSx MaHsxNavigation { get; set; }

    [ForeignKey("MaLoai")]
    [InverseProperty("SanPhams")]
    public virtual LoaiSp MaLoaiNavigation { get; set; }

    [ForeignKey("MaNcc")]
    [InverseProperty("SanPhams")]
    public virtual NhaCc MaNccNavigation { get; set; }
}