// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("Tinh")]
public partial class Tinh
{
    [Key]
    public short MaTinh { get; set; }

    [Required]
    [StringLength(50)]
    public string TenTinh { get; set; }

    [InverseProperty("MaTinhNavigation")]
    public virtual ICollection<Xa> Xas { get; set; } = new List<Xa>();
}