// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QLBH_LeVanHoa_65131052.Models;

[Table("Xa")]
public partial class Xa
{
    [Key]
    public short MaXa { get; set; }

    [Required]
    [StringLength(50)]
    public string TenXa { get; set; }

    public short MaTinh { get; set; }

    [InverseProperty("MaXaNavigation")]
    public virtual ICollection<KhachHang> KhachHangs { get; set; } = new List<KhachHang>();

    [ForeignKey("MaTinh")]
    [InverseProperty("Xas")]
    public virtual Tinh MaTinhNavigation { get; set; }

    [InverseProperty("MaXaNavigation")]
    public virtual ICollection<NhaCc> NhaCcs { get; set; } = new List<NhaCc>();
}